version: '3.9'

services:
  db:
    image: postgres:15
    container_name: savdo_db
    restart: always
    environment:
      POSTGRES_USER: savdo_user
      POSTGRES_PASSWORD: savdo_pass
      POSTGRES_DB: savdo_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build:
      context: .          # root papka: Savdo/
      dockerfile: docker/Dockerfile
    container_name: savdo_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://savdo_user:savdo_pass@db:5432/savdo_db

  nginx:
    image: nginx:latest
    container_name: savdo_nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
